name: 'Deploy to Azure with Terraform'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  infrasetup:
    runs-on: ubuntu-latest
    env:
      TF_ENV: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        auth-type: 'SERVICE_PRINCIPAL'
        
    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Validate'
      run: terraform validate

    - name: Change to Terraform directory
      run: cd "${{ github.workspace }}/terraform-project"

    - name: 'Terraform Plan'
      run: terraform plan --var-file="${{ github.workspace }}/terraform-project/environment/${{ env.TF_ENV }}.tfvars"

    - name: 'Terraform Apply'
      run: terraform apply --var-file="${{ github.workspace }}/terraform-project/environment/${{ env.TF_ENV }}.tfvars" -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
