name: 'Deploy to Azure with Terraform'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  infrasetup:
    runs-on: ubuntu-latest
    env:
      TF_ENV: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        auth-type: 'SERVICE_PRINCIPAL'
        
    - name: List Terraform directory contents
      run: ls -la /home/runner/work/Infrasetup/Infrasetup/terraform-project/
      working-directory: /home/runner/work/Infrasetup/Infrasetup/terraform-project/

    - name: Initialize Terraform
      run: terraform init
      working-directory: /home/runner/work/Infrasetup/Infrasetup/terraform-project/

    - name: 'Terraform Validate'
      run: terraform validate

    - name: Change to Terraform directory
      run: cd /home/runner/work/Infrasetup/Infrasetup/terraform-project/

    - name: Change to Terraform directory
      run: ls -la

    - name: 'Terraform Plan'
      run: terraform plan --var-file="${{ github.workspace }}/terraform-project/environment/${{ env.TF_ENV }}.tfvars"

    - name: 'Terraform Apply'
      run: terraform apply --var-file="${{ github.workspace }}/terraform-project/environment/${{ env.TF_ENV }}.tfvars" -auto-approve

